#!/bin/bash

git clone https://thompsonsed@bitbucket.org/thompsonsed/pycoalescence.git
cd pycoalescence
git checkout develop
cd pycoalescence/lib
rm necsim
git clone https://thompsonsed@bitbucket.org/thompsonsed/necsim.git
cd ../../
python setup.py install